// Code generated by protoc-gen-go.
// source: examples/examplepb/a_bit_of_everything.proto
// DO NOT EDIT!

package examplepb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gengo/grpc-gateway/third_party/googleapis/google/api"
import gengo_grpc_gateway_examples_sub "github.com/gengo/grpc-gateway/examples/sub"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ABitOfEverything struct {
	Uuid         string                     `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
	Nested       []*ABitOfEverything_Nested `protobuf:"bytes,2,rep,name=nested" json:"nested,omitempty"`
	FloatValue   float32                    `protobuf:"fixed32,3,opt,name=float_value" json:"float_value,omitempty"`
	DoubleValue  float64                    `protobuf:"fixed64,4,opt,name=double_value" json:"double_value,omitempty"`
	Int64Value   int64                      `protobuf:"varint,5,opt,name=int64_value" json:"int64_value,omitempty"`
	Uint64Value  uint64                     `protobuf:"varint,6,opt,name=uint64_value" json:"uint64_value,omitempty"`
	Int32Value   int32                      `protobuf:"varint,7,opt,name=int32_value" json:"int32_value,omitempty"`
	Fixed64Value uint64                     `protobuf:"fixed64,8,opt,name=fixed64_value" json:"fixed64_value,omitempty"`
	Fixed32Value uint32                     `protobuf:"fixed32,9,opt,name=fixed32_value" json:"fixed32_value,omitempty"`
	BoolValue    bool                       `protobuf:"varint,10,opt,name=bool_value" json:"bool_value,omitempty"`
	StringValue  string                     `protobuf:"bytes,11,opt,name=string_value" json:"string_value,omitempty"`
	BytesValue   []byte                     `protobuf:"bytes,12,opt,name=bytes_value,proto3" json:"bytes_value,omitempty"`
	Uint32Value  uint32                     `protobuf:"varint,13,opt,name=uint32_value" json:"uint32_value,omitempty"`
	// TODO(yugui) add enum_value
	Sfixed32Value int32 `protobuf:"fixed32,15,opt,name=sfixed32_value" json:"sfixed32_value,omitempty"`
	Sfixed64Value int64 `protobuf:"fixed64,16,opt,name=sfixed64_value" json:"sfixed64_value,omitempty"`
	Sint32Value   int32 `protobuf:"zigzag32,17,opt,name=sint32_value" json:"sint32_value,omitempty"`
	Sint64Value   int64 `protobuf:"zigzag64,18,opt,name=sint64_value" json:"sint64_value,omitempty"`
}

func (m *ABitOfEverything) Reset()                    { *m = ABitOfEverything{} }
func (m *ABitOfEverything) String() string            { return proto.CompactTextString(m) }
func (*ABitOfEverything) ProtoMessage()               {}
func (*ABitOfEverything) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *ABitOfEverything) GetNested() []*ABitOfEverything_Nested {
	if m != nil {
		return m.Nested
	}
	return nil
}

type ABitOfEverything_Nested struct {
	Name   string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Amount uint32 `protobuf:"varint,2,opt,name=amount" json:"amount,omitempty"`
}

func (m *ABitOfEverything_Nested) Reset()                    { *m = ABitOfEverything_Nested{} }
func (m *ABitOfEverything_Nested) String() string            { return proto.CompactTextString(m) }
func (*ABitOfEverything_Nested) ProtoMessage()               {}
func (*ABitOfEverything_Nested) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

type EmptyMessage struct {
}

func (m *EmptyMessage) Reset()                    { *m = EmptyMessage{} }
func (m *EmptyMessage) String() string            { return proto.CompactTextString(m) }
func (*EmptyMessage) ProtoMessage()               {}
func (*EmptyMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type IdMessage struct {
	Uuid string `protobuf:"bytes,1,opt,name=uuid" json:"uuid,omitempty"`
}

func (m *IdMessage) Reset()                    { *m = IdMessage{} }
func (m *IdMessage) String() string            { return proto.CompactTextString(m) }
func (*IdMessage) ProtoMessage()               {}
func (*IdMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func init() {
	proto.RegisterType((*ABitOfEverything)(nil), "gengo.grpc.gateway.examples.examplepb.ABitOfEverything")
	proto.RegisterType((*ABitOfEverything_Nested)(nil), "gengo.grpc.gateway.examples.examplepb.ABitOfEverything.Nested")
	proto.RegisterType((*EmptyMessage)(nil), "gengo.grpc.gateway.examples.examplepb.EmptyMessage")
	proto.RegisterType((*IdMessage)(nil), "gengo.grpc.gateway.examples.examplepb.IdMessage")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for ABitOfEverythingService service

type ABitOfEverythingServiceClient interface {
	Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error)
	BulkCreate(ctx context.Context, opts ...grpc.CallOption) (ABitOfEverythingService_BulkCreateClient, error)
	Lookup(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error)
	List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (ABitOfEverythingService_ListClient, error)
	Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*EmptyMessage, error)
	Delete(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
	Echo(ctx context.Context, in *gengo_grpc_gateway_examples_sub.StringMessage, opts ...grpc.CallOption) (*gengo_grpc_gateway_examples_sub.StringMessage, error)
	BulkEcho(ctx context.Context, opts ...grpc.CallOption) (ABitOfEverythingService_BulkEchoClient, error)
}

type aBitOfEverythingServiceClient struct {
	cc *grpc.ClientConn
}

func NewABitOfEverythingServiceClient(cc *grpc.ClientConn) ABitOfEverythingServiceClient {
	return &aBitOfEverythingServiceClient{cc}
}

func (c *aBitOfEverythingServiceClient) Create(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) CreateBody(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/CreateBody", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) BulkCreate(ctx context.Context, opts ...grpc.CallOption) (ABitOfEverythingService_BulkCreateClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ABitOfEverythingService_serviceDesc.Streams[0], c.cc, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/BulkCreate", opts...)
	if err != nil {
		return nil, err
	}
	x := &aBitOfEverythingServiceBulkCreateClient{stream}
	return x, nil
}

type ABitOfEverythingService_BulkCreateClient interface {
	Send(*ABitOfEverything) error
	CloseAndRecv() (*EmptyMessage, error)
	grpc.ClientStream
}

type aBitOfEverythingServiceBulkCreateClient struct {
	grpc.ClientStream
}

func (x *aBitOfEverythingServiceBulkCreateClient) Send(m *ABitOfEverything) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aBitOfEverythingServiceBulkCreateClient) CloseAndRecv() (*EmptyMessage, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EmptyMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aBitOfEverythingServiceClient) Lookup(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*ABitOfEverything, error) {
	out := new(ABitOfEverything)
	err := grpc.Invoke(ctx, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/Lookup", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) List(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (ABitOfEverythingService_ListClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ABitOfEverythingService_serviceDesc.Streams[1], c.cc, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/List", opts...)
	if err != nil {
		return nil, err
	}
	x := &aBitOfEverythingServiceListClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ABitOfEverythingService_ListClient interface {
	Recv() (*ABitOfEverything, error)
	grpc.ClientStream
}

type aBitOfEverythingServiceListClient struct {
	grpc.ClientStream
}

func (x *aBitOfEverythingServiceListClient) Recv() (*ABitOfEverything, error) {
	m := new(ABitOfEverything)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aBitOfEverythingServiceClient) Update(ctx context.Context, in *ABitOfEverything, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Delete(ctx context.Context, in *IdMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	out := new(EmptyMessage)
	err := grpc.Invoke(ctx, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) Echo(ctx context.Context, in *gengo_grpc_gateway_examples_sub.StringMessage, opts ...grpc.CallOption) (*gengo_grpc_gateway_examples_sub.StringMessage, error) {
	out := new(gengo_grpc_gateway_examples_sub.StringMessage)
	err := grpc.Invoke(ctx, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/Echo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aBitOfEverythingServiceClient) BulkEcho(ctx context.Context, opts ...grpc.CallOption) (ABitOfEverythingService_BulkEchoClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ABitOfEverythingService_serviceDesc.Streams[2], c.cc, "/gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService/BulkEcho", opts...)
	if err != nil {
		return nil, err
	}
	x := &aBitOfEverythingServiceBulkEchoClient{stream}
	return x, nil
}

type ABitOfEverythingService_BulkEchoClient interface {
	Send(*gengo_grpc_gateway_examples_sub.StringMessage) error
	Recv() (*gengo_grpc_gateway_examples_sub.StringMessage, error)
	grpc.ClientStream
}

type aBitOfEverythingServiceBulkEchoClient struct {
	grpc.ClientStream
}

func (x *aBitOfEverythingServiceBulkEchoClient) Send(m *gengo_grpc_gateway_examples_sub.StringMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *aBitOfEverythingServiceBulkEchoClient) Recv() (*gengo_grpc_gateway_examples_sub.StringMessage, error) {
	m := new(gengo_grpc_gateway_examples_sub.StringMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for ABitOfEverythingService service

type ABitOfEverythingServiceServer interface {
	Create(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	CreateBody(context.Context, *ABitOfEverything) (*ABitOfEverything, error)
	BulkCreate(ABitOfEverythingService_BulkCreateServer) error
	Lookup(context.Context, *IdMessage) (*ABitOfEverything, error)
	List(*EmptyMessage, ABitOfEverythingService_ListServer) error
	Update(context.Context, *ABitOfEverything) (*EmptyMessage, error)
	Delete(context.Context, *IdMessage) (*EmptyMessage, error)
	Echo(context.Context, *gengo_grpc_gateway_examples_sub.StringMessage) (*gengo_grpc_gateway_examples_sub.StringMessage, error)
	BulkEcho(ABitOfEverythingService_BulkEchoServer) error
}

func RegisterABitOfEverythingServiceServer(s *grpc.Server, srv ABitOfEverythingServiceServer) {
	s.RegisterService(&_ABitOfEverythingService_serviceDesc, srv)
}

func _ABitOfEverythingService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ABitOfEverythingServiceServer).Create(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ABitOfEverythingService_CreateBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ABitOfEverythingServiceServer).CreateBody(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ABitOfEverythingService_BulkCreate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ABitOfEverythingServiceServer).BulkCreate(&aBitOfEverythingServiceBulkCreateServer{stream})
}

type ABitOfEverythingService_BulkCreateServer interface {
	SendAndClose(*EmptyMessage) error
	Recv() (*ABitOfEverything, error)
	grpc.ServerStream
}

type aBitOfEverythingServiceBulkCreateServer struct {
	grpc.ServerStream
}

func (x *aBitOfEverythingServiceBulkCreateServer) SendAndClose(m *EmptyMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aBitOfEverythingServiceBulkCreateServer) Recv() (*ABitOfEverything, error) {
	m := new(ABitOfEverything)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ABitOfEverythingService_Lookup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ABitOfEverythingServiceServer).Lookup(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ABitOfEverythingService_List_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyMessage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ABitOfEverythingServiceServer).List(m, &aBitOfEverythingServiceListServer{stream})
}

type ABitOfEverythingService_ListServer interface {
	Send(*ABitOfEverything) error
	grpc.ServerStream
}

type aBitOfEverythingServiceListServer struct {
	grpc.ServerStream
}

func (x *aBitOfEverythingServiceListServer) Send(m *ABitOfEverything) error {
	return x.ServerStream.SendMsg(m)
}

func _ABitOfEverythingService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(ABitOfEverything)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ABitOfEverythingServiceServer).Update(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ABitOfEverythingService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(IdMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ABitOfEverythingServiceServer).Delete(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ABitOfEverythingService_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(gengo_grpc_gateway_examples_sub.StringMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(ABitOfEverythingServiceServer).Echo(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _ABitOfEverythingService_BulkEcho_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ABitOfEverythingServiceServer).BulkEcho(&aBitOfEverythingServiceBulkEchoServer{stream})
}

type ABitOfEverythingService_BulkEchoServer interface {
	Send(*gengo_grpc_gateway_examples_sub.StringMessage) error
	Recv() (*gengo_grpc_gateway_examples_sub.StringMessage, error)
	grpc.ServerStream
}

type aBitOfEverythingServiceBulkEchoServer struct {
	grpc.ServerStream
}

func (x *aBitOfEverythingServiceBulkEchoServer) Send(m *gengo_grpc_gateway_examples_sub.StringMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *aBitOfEverythingServiceBulkEchoServer) Recv() (*gengo_grpc_gateway_examples_sub.StringMessage, error) {
	m := new(gengo_grpc_gateway_examples_sub.StringMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _ABitOfEverythingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gengo.grpc.gateway.examples.examplepb.ABitOfEverythingService",
	HandlerType: (*ABitOfEverythingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ABitOfEverythingService_Create_Handler,
		},
		{
			MethodName: "CreateBody",
			Handler:    _ABitOfEverythingService_CreateBody_Handler,
		},
		{
			MethodName: "Lookup",
			Handler:    _ABitOfEverythingService_Lookup_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ABitOfEverythingService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ABitOfEverythingService_Delete_Handler,
		},
		{
			MethodName: "Echo",
			Handler:    _ABitOfEverythingService_Echo_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkCreate",
			Handler:       _ABitOfEverythingService_BulkCreate_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "List",
			Handler:       _ABitOfEverythingService_List_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BulkEcho",
			Handler:       _ABitOfEverythingService_BulkEcho_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor1 = []byte{
	// 758 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x96, 0xdf, 0x6a, 0x13, 0x41,
	0x14, 0xc6, 0xd9, 0x24, 0xdd, 0x36, 0x93, 0x34, 0x4d, 0xc7, 0x7f, 0x6d, 0x10, 0xac, 0x4b, 0xad,
	0x35, 0x96, 0x9d, 0x36, 0x15, 0x85, 0x82, 0x82, 0xd1, 0x5e, 0x08, 0xb5, 0x5e, 0x14, 0x6f, 0x0a,
	0x12, 0x66, 0x93, 0xc9, 0x76, 0xe9, 0x66, 0x67, 0xd9, 0x9d, 0x8d, 0x0d, 0x21, 0x37, 0xbe, 0x82,
	0x20, 0x08, 0x8a, 0x82, 0x57, 0x0a, 0x3e, 0x89, 0x97, 0xbe, 0x81, 0xf8, 0x20, 0x9e, 0x9d, 0x6c,
	0xb6, 0x9b, 0x28, 0x26, 0x8d, 0x50, 0xef, 0x32, 0xbf, 0x39, 0x73, 0xce, 0x97, 0xf3, 0x9d, 0x99,
	0x04, 0x6d, 0xb0, 0x13, 0xda, 0x72, 0x6d, 0xe6, 0x93, 0xe8, 0x83, 0x6b, 0x10, 0x5a, 0x33, 0x2c,
	0x51, 0xe3, 0xcd, 0x1a, 0x6b, 0x33, 0xaf, 0x23, 0x8e, 0x2c, 0xc7, 0xd4, 0x5d, 0x8f, 0x0b, 0x8e,
	0x6f, 0x98, 0xcc, 0x31, 0xb9, 0x6e, 0x7a, 0x6e, 0x5d, 0x37, 0xa9, 0x60, 0x2f, 0x69, 0x47, 0x1f,
	0x24, 0xd0, 0xe3, 0x04, 0xa5, 0xab, 0x26, 0xe7, 0xa6, 0xcd, 0x08, 0x75, 0x2d, 0x42, 0x1d, 0x87,
	0x0b, 0x2a, 0x2c, 0xee, 0xf8, 0xfd, 0x24, 0xa5, 0x52, 0x5c, 0xd2, 0x0f, 0x0c, 0xd2, 0x62, 0xbe,
	0x4f, 0x4d, 0xd6, 0xdf, 0xd3, 0x7e, 0xa4, 0x51, 0xf1, 0x61, 0xd5, 0x12, 0xcf, 0x9a, 0xbb, 0x71,
	0x6d, 0x9c, 0x47, 0x99, 0x20, 0xb0, 0x1a, 0x4b, 0xca, 0x8a, 0xb2, 0x9e, 0xc5, 0xfb, 0x48, 0x75,
	0x98, 0x2f, 0x58, 0x63, 0x29, 0xb5, 0x92, 0x5e, 0xcf, 0x55, 0x1e, 0xe8, 0x13, 0x89, 0xd2, 0x47,
	0xd3, 0xea, 0xfb, 0x32, 0x0b, 0xbe, 0x80, 0x72, 0x4d, 0x9b, 0x53, 0x51, 0x6b, 0x53, 0x3b, 0x60,
	0x4b, 0x69, 0x28, 0x92, 0xc2, 0x17, 0x51, 0xbe, 0xc1, 0x03, 0xc3, 0x66, 0x11, 0xcd, 0x00, 0x55,
	0xc2, 0x50, 0xcb, 0x11, 0x77, 0xef, 0x44, 0x70, 0x06, 0x60, 0x3a, 0x0c, 0x0d, 0x92, 0x54, 0x05,
	0x9a, 0x89, 0x42, 0xb7, 0x2b, 0x11, 0x9c, 0x05, 0x38, 0x83, 0x2f, 0xa1, 0xf9, 0xa6, 0x75, 0xc2,
	0x1a, 0x71, 0xec, 0x1c, 0x60, 0x35, 0xc6, 0x71, 0x74, 0x16, 0xf0, 0x2c, 0xc6, 0x08, 0x19, 0x9c,
	0xdb, 0x11, 0x43, 0xc0, 0xe6, 0xc2, 0x62, 0xbe, 0xf0, 0x40, 0x7d, 0x44, 0x73, 0xb2, 0x25, 0x50,
	0xcc, 0xe8, 0x08, 0xe6, 0x47, 0x30, 0x0f, 0x30, 0x3f, 0xd0, 0x15, 0x27, 0x9d, 0x07, 0x3a, 0x8f,
	0x2f, 0xa3, 0x82, 0x3f, 0x5c, 0x6c, 0x01, 0xf8, 0xc2, 0x29, 0x8f, 0xb5, 0x15, 0x81, 0x17, 0x65,
	0xc1, 0x64, 0x96, 0x45, 0xa0, 0x8b, 0x03, 0x1a, 0xc7, 0x62, 0xa0, 0xb8, 0xb4, 0x86, 0xd4, 0xa8,
	0xa7, 0xe0, 0x98, 0x43, 0x5b, 0x2c, 0x72, 0xac, 0x80, 0x54, 0xda, 0xe2, 0x81, 0x23, 0xc0, 0x31,
	0xd0, 0xa0, 0x15, 0x50, 0x7e, 0xb7, 0xe5, 0x8a, 0xce, 0xd3, 0xbe, 0xf5, 0xda, 0x32, 0xca, 0x3e,
	0x69, 0x44, 0x8b, 0x61, 0xb3, 0x2b, 0xef, 0x0a, 0xe8, 0xca, 0xa8, 0x71, 0x07, 0xcc, 0x6b, 0x5b,
	0x75, 0x86, 0xdf, 0xa7, 0x91, 0xfa, 0xc8, 0x63, 0xe0, 0x38, 0xbe, 0x37, 0xe5, 0x0c, 0x94, 0xa6,
	0x3d, 0xa8, 0x7d, 0x4c, 0xbd, 0xfa, 0xfe, 0xf3, 0x75, 0xea, 0x6d, 0x4a, 0x7b, 0x93, 0x22, 0xed,
	0xad, 0xc1, 0xed, 0xf9, 0xd3, 0xdd, 0x21, 0xdd, 0xc4, 0x7c, 0xf5, 0x48, 0x37, 0x39, 0x58, 0xb0,
	0x4c, 0xf4, 0xb1, 0x47, 0x7c, 0xe6, 0x52, 0x8f, 0x0a, 0xee, 0x91, 0x6e, 0x30, 0xb4, 0xd1, 0x4d,
	0x98, 0x00, 0xab, 0x21, 0xab, 0x06, 0xeb, 0xc4, 0xfe, 0xe9, 0xe0, 0xc0, 0x22, 0x39, 0x31, 0xf7,
	0x61, 0xe1, 0x7a, 0x0c, 0xe2, 0x49, 0xb9, 0xd7, 0x2f, 0x92, 0x3c, 0x76, 0x3a, 0x45, 0xe1, 0xb9,
	0xd1, 0xac, 0xfe, 0x68, 0x59, 0x7f, 0xf8, 0x78, 0x72, 0x26, 0x7a, 0xf8, 0x8b, 0x82, 0x50, 0xdf,
	0x9f, 0x2a, 0x6f, 0x74, 0xfe, 0x83, 0x47, 0x65, 0x69, 0xd1, 0xaa, 0x76, 0x6d, 0x8c, 0x41, 0x3b,
	0x4a, 0x19, 0x7f, 0x05, 0xb1, 0xd5, 0xc0, 0x3e, 0xfe, 0xd7, 0x81, 0xda, 0x9e, 0xf0, 0xe0, 0xd0,
	0x05, 0x20, 0x52, 0xe8, 0x2d, 0x6d, 0x75, 0xdc, 0x24, 0x19, 0xa0, 0x10, 0xd4, 0xc2, 0x53, 0xf4,
	0x49, 0x41, 0xea, 0x1e, 0xe7, 0xc7, 0x81, 0x8b, 0x37, 0x27, 0x2c, 0x19, 0xdf, 0xb1, 0xe9, 0x3b,
	0xaa, 0x4b, 0xa1, 0xeb, 0x78, 0x6d, 0xec, 0xc8, 0x87, 0x77, 0xb8, 0x87, 0x3f, 0x28, 0x28, 0xb3,
	0x67, 0xf9, 0x02, 0x4f, 0xd3, 0x96, 0xe9, 0x65, 0xde, 0x94, 0x32, 0xaf, 0xe3, 0x71, 0xc6, 0x6f,
	0x2a, 0xf8, 0x33, 0xf4, 0xf1, 0xb9, 0xdb, 0x38, 0x7f, 0xcf, 0xb7, 0xa4, 0xc6, 0xdb, 0xa5, 0x09,
	0x5b, 0x19, 0xce, 0x28, 0x74, 0x53, 0x7d, 0xcc, 0x6c, 0x06, 0x5a, 0xcf, 0xee, 0xf9, 0x54, 0x22,
	0x23, 0xbf, 0xcb, 0x93, 0xfa, 0xfd, 0x0d, 0xfc, 0xde, 0xad, 0x1f, 0x71, 0xac, 0xff, 0xb5, 0x1a,
	0xfc, 0xee, 0xeb, 0x07, 0xf2, 0x51, 0x1a, 0xa8, 0x3b, 0x63, 0xbc, 0x56, 0x97, 0xc2, 0x5e, 0xe0,
	0x8d, 0x71, 0xc2, 0x18, 0xa8, 0x21, 0xdd, 0xfe, 0x8b, 0x74, 0xb8, 0xac, 0x15, 0x49, 0xbb, 0x12,
	0xc7, 0x87, 0x7b, 0x3b, 0x33, 0x72, 0xef, 0x10, 0xe3, 0xdf, 0xb6, 0xc2, 0x7e, 0xcf, 0x85, 0x6f,
	0xc2, 0xb9, 0x7c, 0xa3, 0x89, 0xdf, 0x00, 0xa9, 0x3a, 0x7c, 0x03, 0x36, 0x95, 0x6a, 0xee, 0x30,
	0x1b, 0x3b, 0x67, 0xa8, 0xf2, 0x2f, 0xd4, 0xf6, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xfe,
	0xd0, 0xd8, 0xd3, 0x09, 0x00, 0x00,
}
